ersion: '3.8'

services:
  vault:
    image: vault:1.13.3
    container_name: vault
    ports:
      - "8200:8200"
    volumes:
      - ./data:/vault/file
      - ./config/vault-config.json:/vault/config/vault-config.json
    networks:
      - vault-net
    command: ["vault", "server", "-config=/vault/config/vault-config.json"]
    restart: always
 
networks:
  vault-net:
    driver: bridge